In [3]:
#from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)
torch.cuda.is_available()

tensor([[0.1696, 0.1953, 0.2245],
        [0.7223, 0.7640, 0.8226],
        [0.8671, 0.4031, 0.0212],
        [0.1292, 0.8790, 0.1453],
        [0.0052, 0.3124, 0.1165]])


False

In [5]:
# create empty matrix(5x3)
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000,  0.0000, -0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.0000]])


In [6]:
# construct rand matrix
ran = torch.rand(5,3)
print(ran)

tensor([[0.3282, 0.1871, 0.0882],
        [0.5953, 0.1108, 0.0410],
        [0.9958, 0.7133, 0.4293],
        [0.3072, 0.7386, 0.2411],
        [0.7703, 0.2735, 0.9469]])


In [8]:
# init matrix with dtype
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
# contruct direct from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
print(x.size())

torch.Size([2])


In [15]:
# operation
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a)
print(b)
print(a+b)
print(torch.add(a,b))

result = torch.empty(2,2)
print(result)
print(torch.add(a,b, out=result))
print(result)

tensor([[0.4772, 0.6058],
        [0.0071, 0.5140]])
tensor([[0.5554, 0.8274],
        [0.5888, 0.2612]])
tensor([[1.0326, 1.4332],
        [0.5960, 0.7753]])
tensor([[1.0326, 1.4332],
        [0.5960, 0.7753]])
tensor([[ 0.0000e+00,  4.6566e-10],
        [-2.4594e-36,  8.5920e+09]])
tensor([[1.0326, 1.4332],
        [0.5960, 0.7753]])
tensor([[1.0326, 1.4332],
        [0.5960, 0.7753]])
