In [2]:
# First import torch
import torch
torch.__version__

'0.4.1'

In [2]:
def activation(x):
    """Sigmoid activation"""
    return 1/ (1 + torch.exp(-x))

In [26]:
# Generate some data
torch.manual_seed(7)# Set random seed so it can predictable

#features
features = torch.randn((1,5))
print(features)
#weights
weights = torch.rand_like(features)
print(weights)
#bias
bias = torch.rand((1,1))
print(bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[0.2868, 0.2063, 0.4451, 0.3593, 0.7204]])
tensor([[0.0731]])


In [27]:
y = activation(torch.sum(features*weights) + bias)
print(y)
y = activation((features*weights).sum() + bias)
print(y)

tensor([[0.8072]])
tensor([[0.8072]])


In [42]:
#torch.mm(features, weights)

# get feature shape
print(features.shape)
# reshape weights
print(weights)
print(weights.reshape(5,1))
#print(weights.resize_(5,1))
print(weights.view(5,1))# recommended one

y = activation(torch.sum(torch.mm(features, weights.view(5,1))) + bias)
print(y)

torch.Size([1, 5])
tensor([[0.2868, 0.2063, 0.4451, 0.3593, 0.7204]])
tensor([[0.2868],
        [0.2063],
        [0.4451],
        [0.3593],
        [0.7204]])
tensor([[0.2868],
        [0.2063],
        [0.4451],
        [0.3593],
        [0.7204]])
tensor([[0.8072]])


In [45]:
# Multi layer NN
#generate sample data
torch.manual_seed(7) #random that predictable

#features (of 3)
features = torch.randn((1,3))
print(features)
#defince the size of each layer in NN
n_input = features.shape[1] #number of input unit
n_hidden = 2
n_output = 1
print(n_input)

#weight for input  hidden layer
W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)
print(W1)
print(W2)

#bias 
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))
print(B1)
print(B2)


tensor([[-0.1468,  0.7861,  0.9468]])
3
tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])
tensor([[-1.6822],
        [ 0.3177]])
tensor([[0.1328, 0.1373]])
tensor([[0.2405]])


In [46]:
# calculate n layer multi
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


In [47]:
# Torch to numpy and back
import numpy as np
a = np.random.rand(4,3)
a

array([[ 0.18262585,  0.45328796,  0.87750313],
       [ 0.96311394,  0.58370017,  0.31751897],
       [ 0.7276381 ,  0.04311922,  0.62620105],
       [ 0.74497737,  0.26965519,  0.95155561]])

In [48]:
b = torch.from_numpy(a)
b

tensor([[0.1826, 0.4533, 0.8775],
        [0.9631, 0.5837, 0.3175],
        [0.7276, 0.0431, 0.6262],
        [0.7450, 0.2697, 0.9516]], dtype=torch.float64)

In [53]:
#multi torch by 2, in place operation
b.mul_(2)
b

tensor([[0.7305, 1.8132, 3.5100],
        [3.8525, 2.3348, 1.2701],
        [2.9106, 0.1725, 2.5048],
        [2.9799, 1.0786, 3.8062]], dtype=torch.float64)

In [54]:
# a valute also change
a

array([[ 0.73050341,  1.81315186,  3.5100125 ],
       [ 3.85245576,  2.33480066,  1.27007587],
       [ 2.9105524 ,  0.1724769 ,  2.50480419],
       [ 2.97990948,  1.07862077,  3.80622243]])